# Generated by Django 5.2.6 on 2025-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_account", "0004_alter_customuser_is_active_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
